version: 2.1
executors:
  linux:
    docker:
      - image: circleci/node:14-browsers
  macos:
    macos:
      xcode: "12.4.0"
commands:
  yarn_install:
    steps:
      - restore_cache:
          name: Restoring dependency cache
          key: yarn-v9-{{arch}}-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Saving dependency cache
          key: yarn-v9-{{arch}}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/AppData/Local/Yarn/Cache
            - ~/Library/Caches/Yarn
  prepack:
    steps:
      - run:
          name: Prepack
          command: yarn prepack

jobs:
  prepack:
    executor: <<parameters.executor>>
    parameters:
      executor:
        type: executor
        default: "linux"
    steps:
      - checkout
      - yarn_install
      - prepack
      - persist_to_workspace:
          root: .
          paths:
            - "packages/*/dist"
  test:
    executor: <<parameters.executor>>
    parameters:
      scope:
        type: string
        default: "interactors"
      package:
        type: string
      driver:
        type: string
        default: "default"
      executor:
        type: executor
        default: "linux"
      prepack:
        type: boolean
        default: true
    environment:
      DRIVER: <<parameters.driver>>
    steps:
      - checkout
      - yarn_install
      - when:
          condition: <<parameters.prepack>>
          steps:
            - prepack
      - attach_workspace:
          at: .
      - run:
          name: Running tests
          command: yarn workspace @<<parameters.scope>>/<<parameters.package>> test
  lint:
    executor: <<parameters.executor>>
    parameters:
      executor:
        type: executor
        default: "linux"
      prepack:
        type: boolean
        default: true
    steps:
      - checkout
      - yarn_install
      - when:
          condition: <<parameters.prepack>>
          steps:
            - prepack
      - attach_workspace:
          at: .
      - run:
          name: Running lint
          command: yarn lint
workflows:
  test:
    jobs:
      - prepack
      - test:
          name: "test-<<matrix.package>>"
          prepack: false
          matrix:
            parameters:
              package:
                - html
                - material-ui
                - with-cypress
          requires:
            - prepack
      - lint:
          prepack: false
          requires:
            - prepack