import {
  and,
  every,
  getInteractorConstructorMetadata,
  getMatcherConstructorMetadata,
  including,
  matching,
  not,
  or,
  some,
} from "@interactors/core";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  AGENT_PROTOCOL_VERSION,
  type Registry,
  type RegistryInteractor,
  type RegistryMatcher,
} from "./types.ts";
import { parse as parseJsonc } from "@std/jsonc";

export interface CompileOptions {
  readonly entrypoint: string;
  readonly outdir?: string;
}

export interface CompileResult {
  readonly agentPath: string;
  readonly registryPath: string;
  readonly declarationsPath: string;
  readonly registry: Registry;
}

interface DiscoveredMatcher extends RegistryMatcher {
  readonly source: "builtin" | "entrypoint";
  readonly builtinExport?: string;
}

interface PackageMapping {
  readonly root: string;
  readonly name: string;
}

interface PackageModule {
  readonly specifier: string;
  readonly resolved: string;
}

interface DeclarationImportMapping {
  readonly source: string;
  readonly target: string;
}

interface DependencyMetadata {
  readonly mappings: readonly PackageMapping[];
  readonly modules: readonly PackageModule[];
  readonly imports: readonly DeclarationImportMapping[];
}

interface PublicTypeAlias {
  readonly specifier: string;
  readonly exportName: string;
}

const builtins = { and, every, including, matching, not, or, some } as const;
const reservedInteractorMethods = new Set([
  "absent",
  "apply",
  "assert",
  "description",
  "exists",
  "find",
  "has",
  "is",
  "options",
  "perform",
  "then",
]);

export async function compile(options: CompileOptions): Promise<CompileResult> {
  let entrypoint = resolveInput(options.entrypoint);
  let outdir = resolve(options.outdir ?? "dist");

  await requireFile(entrypoint);

  let { source } = await importEntrypoint(entrypoint);
  let interactors = discoverInteractors(source);
  let matchers = discoverMatchers(source);

  if (interactors.length === 0) {
    throw new Error(
      `No interactor constructors were exported by ${entrypoint}`,
    );
  }

  validateDefinitionIds(interactors, matchers);

  let registry = await createRegistry(interactors, matchers);
  let registryText = `${JSON.stringify(registry, null, 2)}\n`;
  let dependencies = await discoverDependencies(entrypoint);
  let typeAliases = await discoverPublicTypeAliases(
    source,
    [
      ...interactors.map(({ id }) => id),
      ...matchers
        .filter(({ source }) => source === "entrypoint")
        .map(({ id }) => id),
    ],
    dependencies.modules,
  );

  await Deno.mkdir(outdir, { recursive: true });
  let buildDirectory = await Deno.makeTempDir({
    dir: outdir,
    prefix: ".interactors-compile-",
  });

  let agentPath = join(outdir, "agent.js");
  let registryPath = join(outdir, "interactors.json");
  let declarationsPath = join(outdir, "interactors.d.ts");

  try {
    let agentEntrypoint = join(buildDirectory, "agent-entry.ts");
    let bundledAgent = join(buildDirectory, "agent.js");
    let declarationsEntrypoint = join(buildDirectory, "declarations-entry.ts");
    let bundledDeclarations = join(buildDirectory, "interactors.d.ts");

    await Deno.writeTextFile(
      agentEntrypoint,
      generateAgentEntrypoint(entrypoint, registry, matchers),
    );
    await bundleAgent(agentEntrypoint, bundledAgent, dirname(entrypoint));
    let agent = await Deno.readTextFile(bundledAgent);

    await Deno.writeTextFile(
      declarationsEntrypoint,
      generateDeclarationsEntrypoint(
        entrypoint,
        interactors,
        matchers,
        typeAliases,
      ),
    );
    let declarationConfig = await createDeclarationConfig(entrypoint);
    let declarations: string;
    try {
      await bundleDeclarations(
        declarationsEntrypoint,
        bundledDeclarations,
        dirname(entrypoint),
        declarationConfig,
      );

      declarations = await finalizeDeclarations(
        bundledDeclarations,
        registry.registryHash,
        dependencies.mappings,
        dependencies.imports,
        typeAliases,
      );
      let checkedDeclarations = join(buildDirectory, "checked-interactors.ts");
      await Deno.writeTextFile(checkedDeclarations, declarations);
      await checkDeclarations(
        checkedDeclarations,
        dirname(entrypoint),
        declarationConfig,
      );
    } finally {
      await Deno.remove(declarationConfig);
    }

    await Deno.writeTextFile(
      agentPath,
      `// Generated by @interactors/cli. Do not edit.\n// Registry: ${registry.registryHash}\n${
        wrapBrowserBundle(agent)
      }`,
    );
    await Deno.writeTextFile(registryPath, registryText);
    await Deno.writeTextFile(declarationsPath, declarations);
  } finally {
    await Deno.remove(buildDirectory, { recursive: true });
  }

  return { agentPath, registryPath, declarationsPath, registry };
}

async function importEntrypoint(
  entrypoint: string,
): Promise<{ readonly source: Record<string, unknown> }> {
  let sourceUrl = new URL(pathToFileURL(entrypoint));
  sourceUrl.searchParams.set("interactors-compile", crypto.randomUUID());
  let wrapper = `import * as definitions from ${
    JSON.stringify(sourceUrl.href)
  };\nexport default definitions;\n`;
  let wrapperUrl = `data:text/javascript,${encodeURIComponent(wrapper)}`;
  let imported = await import(wrapperUrl) as {
    readonly default: Record<string, unknown>;
  };
  // A module namespace may itself export a callable `then`. Keep it boxed so
  // async-function resolution does not treat that namespace as a thenable.
  return { source: imported.default };
}

function wrapBrowserBundle(bundle: string): string {
  return `(function (require) {\n${bundle}\n})(function (specifier) {
  if (specifier !== "events" && specifier !== "node:events") {
    throw new Error("Unsupported browser dependency: " + specifier);
  }

  class EventEmitter {
    constructor() {
      this.listeners = new Map();
    }

    setMaxListeners() {
      return this;
    }

    on(event, listener) {
      let listeners = this.listeners.get(event) || [];
      listeners.push(listener);
      this.listeners.set(event, listeners);
      return this;
    }

    once(event, listener) {
      let wrapped = (...args) => {
        this.off(event, wrapped);
        listener.apply(this, args);
      };
      return this.on(event, wrapped);
    }

    off(event, listener) {
      let listeners = this.listeners.get(event);
      if (listeners) {
        this.listeners.set(event, listeners.filter((item) => item !== listener));
      }
      return this;
    }

    removeListener(event, listener) {
      return this.off(event, listener);
    }

    emit(event, ...args) {
      let listeners = this.listeners.get(event) || [];
      for (let listener of [...listeners]) {
        listener.apply(this, args);
      }
      return listeners.length > 0;
    }
  }

  return { EventEmitter };
});\n`;
}

function resolveInput(path: string): string {
  return isAbsolute(path) ? path : resolve(path);
}

async function requireFile(path: string): Promise<void> {
  let info: Deno.FileInfo;
  try {
    info = await Deno.stat(path);
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      throw new Error(`Interactor entrypoint does not exist: ${path}`);
    }
    throw error;
  }

  if (!info.isFile) {
    throw new Error(`Interactor entrypoint is not a file: ${path}`);
  }
}

function discoverInteractors(
  source: Record<string, unknown>,
): RegistryInteractor[] {
  let interactors: RegistryInteractor[] = [];

  for (let [id, value] of sortedEntries(source)) {
    let metadata = getInteractorConstructorMetadata(value);
    if (metadata) {
      validateDefinitionName("Interactor", id, metadata.name);
      validateInteractorMethods(id, metadata.actions, metadata.filters);
      interactors.push({
        id,
        name: metadata.name,
        actions: [...metadata.actions],
        filters: [...metadata.filters],
      });
    }
  }

  return interactors;
}

function validateInteractorMethods(
  id: string,
  actions: readonly string[],
  filters: readonly string[],
): void {
  let actionNames = new Set(actions);
  for (let name of [...actions, ...filters]) {
    if (name.length === 0) {
      throw new Error(
        `Interactor ${JSON.stringify(id)} declares an empty method name`,
      );
    }
    if (reservedInteractorMethods.has(name)) {
      throw new Error(
        `Interactor ${JSON.stringify(id)} declares reserved method ${
          JSON.stringify(name)
        }`,
      );
    }
    if (actionNames.has(name) && filters.includes(name)) {
      throw new Error(
        `Interactor ${JSON.stringify(id)} declares ${
          JSON.stringify(name)
        } as both an action and a filter`,
      );
    }
  }
}

function discoverMatchers(
  source: Record<string, unknown>,
): DiscoveredMatcher[] {
  let matchers = new Map<string, DiscoveredMatcher>();

  for (let [id, value] of sortedEntries(builtins)) {
    let metadata = getMatcherConstructorMetadata(value);
    if (!metadata) {
      throw new Error(`Built-in matcher ${id} does not expose metadata`);
    }
    validateDefinitionName("Matcher", id, metadata.name);
    matchers.set(id, {
      id,
      name: metadata.name,
      source: "builtin",
      builtinExport: id,
    });
  }

  for (let [id, value] of sortedEntries(source)) {
    let metadata = getMatcherConstructorMetadata(value);
    if (metadata) {
      validateDefinitionName("Matcher", id, metadata.name);
      matchers.set(id, {
        id,
        name: metadata.name,
        source: "entrypoint",
      });
    }
  }

  return [...matchers.values()].sort(byId);
}

function validateDefinitionName(
  kind: "Interactor" | "Matcher",
  id: string,
  name: string,
): void {
  if (name.length === 0) {
    throw new Error(`${kind} ${JSON.stringify(id)} has an empty name`);
  }
}

function validateDefinitionIds(
  interactors: readonly RegistryInteractor[],
  matchers: readonly RegistryMatcher[],
): void {
  let interactorIds = new Set(interactors.map(({ id }) => id));

  for (let definition of [...interactors, ...matchers]) {
    if (definition.id === "then") {
      throw new Error('Interactor definitions cannot be exported as "then"');
    }
  }

  for (let matcher of matchers) {
    if (interactorIds.has(matcher.id)) {
      throw new Error(
        `Definition ${
          JSON.stringify(matcher.id)
        } is exported as both an interactor and a matcher`,
      );
    }
  }
}

async function createRegistry(
  interactors: readonly RegistryInteractor[],
  matchers: readonly RegistryMatcher[],
): Promise<Registry> {
  let content = {
    protocolVersion: AGENT_PROTOCOL_VERSION,
    interactors,
    matchers: matchers.map(({ id, name }) => ({ id, name })),
  };
  let registryHash = await sha256(JSON.stringify(content));

  return {
    protocolVersion: AGENT_PROTOCOL_VERSION,
    registryHash,
    interactors,
    matchers: content.matchers,
  };
}

async function sha256(value: string): Promise<string> {
  let digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(value),
  );
  let hex = [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
  return `sha256:${hex}`;
}

async function discoverPublicTypeAliases(
  source: Record<string, unknown>,
  names: readonly string[],
  modules: readonly PackageModule[],
): Promise<Map<string, PublicTypeAlias>> {
  let aliases = new Map<string, PublicTypeAlias>();

  for (let module of modules) {
    let exports = await import(module.resolved) as Record<string, unknown>;
    for (let [exportName, value] of sortedEntries(exports)) {
      for (let name of names) {
        if (!aliases.has(name) && source[name] === value) {
          aliases.set(name, {
            specifier: module.specifier,
            exportName,
          });
        }
      }
    }
  }

  return aliases;
}

function generateAgentEntrypoint(
  entrypoint: string,
  registry: Registry,
  matchers: readonly DiscoveredMatcher[],
): string {
  let sourceUrl = pathToFileURL(entrypoint).href;
  let runtimeUrl = new URL("./agent.ts", import.meta.url).href;
  let coreUrl = import.meta.resolve("@interactors/core");
  let builtinMatchers = matchers.filter((matcher) =>
    matcher.source === "builtin"
  );
  let builtinImports = builtinMatchers.map((matcher, index) =>
    `${matcher.builtinExport} as __builtinMatcher${index}`
  );
  let matcherValues = matchers.map((matcher) => {
    if (matcher.source === "entrypoint") {
      return `    [${JSON.stringify(matcher.id)}, source[${
        JSON.stringify(matcher.id)
      }]],`;
    }
    let index = builtinMatchers.indexOf(matcher);
    return `    [${JSON.stringify(matcher.id)}, __builtinMatcher${index}],`;
  });
  let interactorValues = registry.interactors.map((interactor) =>
    `    [${JSON.stringify(interactor.id)}, source[${
      JSON.stringify(interactor.id)
    }]],`
  );

  return `import * as source from ${JSON.stringify(sourceUrl)};
import { ${builtinImports.join(", ")} } from ${JSON.stringify(coreUrl)};
import { installAgent } from ${JSON.stringify(runtimeUrl)};

installAgent({
  registry: ${JSON.stringify(registry)},
  interactors: new Map([
${interactorValues.join("\n")}
  ]),
  matchers: new Map([
${matcherValues.join("\n")}
  ]),
});
`;
}

function generateDeclarationsEntrypoint(
  entrypoint: string,
  interactors: readonly RegistryInteractor[],
  matchers: readonly DiscoveredMatcher[],
  typeAliases: ReadonlyMap<string, PublicTypeAlias>,
): string {
  let sourceUrl = pathToFileURL(entrypoint).href;
  let names = [
    ...interactors.map(({ id }) => id),
    ...matchers
      .filter(({ source }) => source === "entrypoint")
      .map(({ id }) => id),
  ].filter((name) => !typeAliases.has(name));

  for (let name of names) {
    if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) || name === "default") {
      throw new Error(
        `Cannot generate declarations for export ${
          JSON.stringify(name)
        }. Interactors and custom matchers must use named exports.`,
      );
    }
  }

  if (names.length === 0) {
    return "export {};\n";
  }

  let imports = names.map((name, index) => `  ${name} as __definition${index}`);
  let exports = names.map((name, index) =>
    `export const ${name} = __definition${index};`
  );

  return `import {\n${imports.join(",\n")}\n} from ${
    JSON.stringify(sourceUrl)
  };\n\n${exports.join("\n")}\n`;
}

async function bundleAgent(
  entrypoint: string,
  outfile: string,
  cwd: string,
): Promise<void> {
  let intermediate = outfile.replace(/\.js$/, ".browser.js");
  await runAgentBundle(
    [
      "--platform=browser",
      "--format=esm",
      "--no-check",
      "--output",
      intermediate,
      entrypoint,
    ],
    cwd,
  );
  await validateBrowserBundle(intermediate, cwd);
  await runAgentBundle(
    [
      "--platform=browser",
      "--format=iife",
      "--minify",
      "--no-check",
      "--output",
      outfile,
      intermediate,
    ],
    cwd,
  );
}

async function runAgentBundle(args: string[], cwd: string): Promise<void> {
  let command = new Deno.Command(Deno.execPath(), {
    cwd,
    args: ["bundle", ...args],
    stdout: "piped",
    stderr: "piped",
  });
  let output = await command.output();

  if (!output.success) {
    let message = new TextDecoder().decode(output.stderr).trim();
    throw new Error(
      `Unable to bundle browser agent${message ? `:\n${message}` : ""}`,
    );
  }
}

async function validateBrowserBundle(path: string, cwd: string): Promise<void> {
  let output = await new Deno.Command(Deno.execPath(), {
    cwd,
    args: ["info", "--json", path],
    stdout: "piped",
    stderr: "piped",
  }).output();

  if (!output.success) {
    let message = new TextDecoder().decode(output.stderr).trim();
    throw new Error(
      `Unable to inspect browser agent${message ? `:\n${message}` : ""}`,
    );
  }

  let info = JSON.parse(new TextDecoder().decode(output.stdout)) as {
    roots?: string[];
    modules?: {
      specifier?: string;
      dependencies?: {
        specifier?: string;
        code?: { specifier?: string; error?: string };
      }[];
    }[];
  };
  let root = info.modules?.find(({ specifier }) =>
    info.roots?.includes(specifier ?? "")
  );
  if (!root) {
    throw new Error(
      "Unable to inspect browser agent: bundled module not found",
    );
  }

  let unsupported = new Set<string>();
  for (let dependency of root.dependencies ?? []) {
    if (dependency.code?.error) {
      unsupported.add(dependency.specifier ?? "<dynamic import>");
    } else if (
      dependency.code?.specifier &&
      dependency.code.specifier !== "events" &&
      dependency.code.specifier !== "node:events"
    ) {
      unsupported.add(dependency.code.specifier);
    }
  }

  if (unsupported.size > 0) {
    throw new Error(
      `Browser agent depends on unsupported external ${
        unsupported.size === 1 ? "module" : "modules"
      }: ${
        [...unsupported].sort().map((specifier) => JSON.stringify(specifier))
          .join(", ")
      }`,
    );
  }
}

async function bundleDeclarations(
  entrypoint: string,
  declarationPath: string,
  cwd: string,
  config: string,
): Promise<void> {
  let outputPath = declarationPath.replace(/\.d\.ts$/, ".js");
  let output = await new Deno.Command(Deno.execPath(), {
    cwd,
    args: [
      "bundle",
      "--declaration",
      "--config",
      config,
      "--packages=external",
      "--platform=deno",
      "--format=esm",
      "--output",
      outputPath,
      entrypoint,
    ],
    stdout: "piped",
    stderr: "piped",
  }).output();

  if (!output.success) {
    let message = new TextDecoder().decode(output.stderr).trim();
    throw new Error(
      `Unable to generate Interactor declarations${
        message ? `:\n${message}` : ""
      }`,
    );
  }
}

async function checkDeclarations(
  path: string,
  cwd: string,
  config: string,
): Promise<void> {
  let output = await new Deno.Command(Deno.execPath(), {
    cwd,
    args: ["check", "--config", config, path],
    stdout: "piped",
    stderr: "piped",
  }).output();

  if (!output.success) {
    let message = new TextDecoder().decode(output.stderr).trim();
    throw new Error(
      `Generated Interactor declarations do not type-check${
        message ? `:\n${message}` : ""
      }`,
    );
  }
}

async function createDeclarationConfig(entrypoint: string): Promise<string> {
  let discovered = await findDenoConfig(dirname(entrypoint));
  let directory = discovered ? dirname(discovered.path) : dirname(entrypoint);
  let config = discovered?.config ?? {};
  let compilerOptions = isRecord(config.compilerOptions)
    ? config.compilerOptions
    : {};
  let scoped = {
    ...config,
    compilerOptions: {
      ...compilerOptions,
      skipLibCheck: true,
    },
  };
  let path = join(
    directory,
    `.interactors-declarations-${crypto.randomUUID()}.json`,
  );

  await Deno.writeTextFile(path, `${JSON.stringify(scoped, null, 2)}\n`, {
    createNew: true,
  });
  return path;
}

async function findDenoConfig(
  start: string,
): Promise<
  | { readonly path: string; readonly config: Record<string, unknown> }
  | undefined
> {
  let nearest:
    | { readonly path: string; readonly config: Record<string, unknown> }
    | undefined;
  let directory = start;

  while (true) {
    for (let filename of ["deno.json", "deno.jsonc"]) {
      let path = join(directory, filename);
      try {
        let parsed = parseJsonc(await Deno.readTextFile(path));
        if (!isRecord(parsed)) {
          throw new Error(`Deno configuration must contain an object: ${path}`);
        }
        let discovered = { path, config: parsed };
        nearest ??= discovered;
        if (parsed.workspace !== undefined) {
          return discovered;
        }
      } catch (error) {
        if (!(error instanceof Deno.errors.NotFound)) {
          throw error;
        }
      }
    }

    let parent = dirname(directory);
    if (parent === directory) {
      return nearest;
    }
    directory = parent;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function finalizeDeclarations(
  path: string,
  registryHash: string,
  packageMappings: readonly PackageMapping[],
  importMappings: readonly DeclarationImportMapping[],
  typeAliases: ReadonlyMap<string, PublicTypeAlias>,
): Promise<string> {
  let declarations = await Deno.readTextFile(path);
  declarations = declarations.replace(
    /(["'])(file:[^"']+)\1/g,
    (original, quote: string, specifier: string) => {
      let imported = importMappings.find(({ source }) => source === specifier);
      if (imported) {
        return `${quote}${imported.target}${quote}`;
      }
      let mapping = packageMappings.find(({ root }) =>
        specifier.startsWith(root)
      );
      return mapping ? `${quote}${mapping.name}${quote}` : original;
    },
  );

  let localImport = declarations.match(
    /(?:import\(|from\s+)["'](file:[^"']+|\.{1,2}\/[^"']+)/,
  );
  if (localImport) {
    throw new Error(
      `Generated declarations depend on local source ${
        JSON.stringify(localImport[1])
      }. Re-export that type from the Interactor entrypoint or define it there.`,
    );
  }

  let aliases = [...typeAliases.entries()]
    .sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0)
    .map(([name, alias]) =>
      `export declare const ${name}: typeof import(${
        JSON.stringify(alias.specifier)
      })[${JSON.stringify(alias.exportName)}];`
    )
    .join("\n");
  let body = [declarations.trim(), aliases].filter(Boolean).join("\n\n");

  return `// Generated by @interactors/cli. Do not edit.\n// Registry: ${registryHash}\n\n${body}\n`;
}

async function discoverDependencies(
  entrypoint: string,
): Promise<DependencyMetadata> {
  let output = await new Deno.Command(Deno.execPath(), {
    cwd: dirname(entrypoint),
    args: ["info", "--json", entrypoint],
    stdout: "piped",
    stderr: "piped",
  }).output();

  if (!output.success) {
    let message = new TextDecoder().decode(output.stderr).trim();
    throw new Error(
      `Unable to inspect Interactor dependencies${
        message ? `:\n${message}` : ""
      }`,
    );
  }

  let info = JSON.parse(new TextDecoder().decode(output.stdout)) as {
    modules?: {
      dependencies?: {
        specifier?: string;
        code?: { specifier?: string };
        type?: { specifier?: string };
      }[];
    }[];
  };
  let mappings = new Map<string, PackageMapping>();
  let modules = new Map<string, PackageModule>();
  let imports = new Map<string, DeclarationImportMapping>();

  for (let module of info.modules ?? []) {
    for (let dependency of module.dependencies ?? []) {
      let requested = dependency.specifier;
      let resolved = dependency.code?.specifier ?? dependency.type?.specifier;

      if (
        !requested || !resolved?.startsWith("file:") ||
        !isBareSpecifier(requested)
      ) {
        continue;
      }

      let name = packageName(requested);
      let root = await findPackageRoot(fileURLToPath(resolved), name);
      if (root) {
        mappings.set(root, { root, name });
        imports.set(`${resolved}\0${requested}`, {
          source: resolved,
          target: requested,
        });
        let code = dependency.code?.specifier;
        if (code?.startsWith("file:")) {
          modules.set(`${requested}\0${code}`, {
            specifier: requested,
            resolved: code,
          });
        }
      }
    }
  }

  return {
    mappings: [...mappings.values()].sort((left, right) =>
      right.root.length - left.root.length
    ),
    modules: [...modules.values()].sort((left, right) =>
      left.specifier < right.specifier
        ? -1
        : left.specifier > right.specifier
        ? 1
        : left.resolved < right.resolved
        ? -1
        : left.resolved > right.resolved
        ? 1
        : 0
    ),
    imports: [...imports.values()].sort((left, right) =>
      left.source < right.source
        ? -1
        : left.source > right.source
        ? 1
        : left.target < right.target
        ? -1
        : left.target > right.target
        ? 1
        : 0
    ),
  };
}

function isBareSpecifier(specifier: string): boolean {
  return !specifier.startsWith(".") &&
    !specifier.startsWith("/") &&
    !/^[a-z][a-z+.-]*:/i.test(specifier);
}

function packageName(specifier: string): string {
  let [first, second] = specifier.split("/");
  return first.startsWith("@") ? `${first}/${second}` : first;
}

async function findPackageRoot(
  modulePath: string,
  expectedName: string,
): Promise<string | undefined> {
  let directory = dirname(modulePath);

  while (true) {
    for (let filename of ["deno.json", "package.json"]) {
      try {
        let manifest = JSON.parse(
          await Deno.readTextFile(join(directory, filename)),
        ) as { name?: string };
        if (manifest.name === expectedName) {
          let root = pathToFileURL(`${directory}/`).href;
          return root.endsWith("/") ? root : `${root}/`;
        }
      } catch (error) {
        if (
          !(error instanceof Deno.errors.NotFound) &&
          !(error instanceof SyntaxError)
        ) {
          throw error;
        }
      }
    }

    let parent = dirname(directory);
    if (parent === directory) {
      return undefined;
    }
    directory = parent;
  }
}

function sortedEntries<T>(value: Record<string, T>): [string, T][] {
  return Object.entries(value).sort(([left], [right]) =>
    left < right ? -1 : left > right ? 1 : 0
  );
}

function byId(left: { id: string }, right: { id: string }): number {
  return left.id < right.id ? -1 : left.id > right.id ? 1 : 0;
}
