import {
  and,
  every,
  getInteractorConstructorMetadata,
  getMatcherConstructorMetadata,
  including,
  matching,
  not,
  or,
  some,
} from "@interactors/core";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";
import { Buffer } from "node:buffer";
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { build, type Plugin } from "esbuild";
import ts from "typescript";
import {
  AGENT_PROTOCOL_VERSION,
  type Registry,
  type RegistryInteractor,
  type RegistryMatcher,
} from "./types.ts";
import { parse as parseJsonc } from "@std/jsonc";
import "./agent.ts";

export interface CompileOptions {
  readonly entrypoint: string;
  readonly outdir?: string;
}

export interface CompileResult {
  readonly agentPath: string;
  readonly registryPath: string;
  readonly declarationsPath: string;
  readonly registry: Registry;
}

interface DiscoveredMatcher extends RegistryMatcher {
  readonly source: "builtin" | "entrypoint";
  readonly builtinExport?: string;
}

const builtins = { and, every, including, matching, not, or, some } as const;
const compilerRequire = createRequire(import.meta.url);
const portableResolver: Plugin = {
  name: "interactors-portable-resolver",
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /^[^./]|^@/ }, async (args) => {
      if (args.pluginData === portableResolver) {
        return;
      }
      let local = await pluginBuild.resolve(args.path, {
        importer: args.importer,
        kind: args.kind,
        namespace: args.namespace,
        pluginData: portableResolver,
        resolveDir: args.resolveDir,
      });
      if (local.errors.length === 0) {
        return local;
      }
      try {
        return { path: compilerRequire.resolve(args.path) };
      } catch {
        try {
          let resolved = import.meta.resolve(args.path);
          return resolved.startsWith("file:")
            ? { path: fileURLToPath(resolved) }
            : local;
        } catch {
          return local;
        }
      }
    });
  },
};
const reservedInteractorMethods = new Set([
  "absent",
  "apply",
  "assert",
  "description",
  "exists",
  "find",
  "has",
  "is",
  "options",
  "perform",
  "then",
]);

export async function compile(options: CompileOptions): Promise<CompileResult> {
  let entrypoint = resolveInput(options.entrypoint);
  let outdir = resolve(options.outdir ?? "dist");

  await requireFile(entrypoint);

  let { source } = await importEntrypoint(entrypoint);
  let interactors = discoverInteractors(source);
  let matchers = discoverMatchers(source);

  if (interactors.length === 0) {
    throw new Error(
      `No interactor constructors were exported by ${entrypoint}`,
    );
  }

  validateDefinitionIds(interactors, matchers);

  let registry = await createRegistry(interactors, matchers);
  let registryText = `${JSON.stringify(registry, null, 2)}\n`;

  await mkdir(outdir, { recursive: true });
  let buildDirectory = await mkdtemp(join(outdir, ".interactors-compile-"));

  let agentPath = join(outdir, "agent.js");
  let registryPath = join(outdir, "interactors.json");
  let declarationsPath = join(outdir, "interactors.d.ts");

  try {
    let agentEntrypoint = join(buildDirectory, "agent-entry.ts");
    let bundledAgent = join(buildDirectory, "agent.js");
    let declarationsEntrypoint = join(buildDirectory, "declarations-entry.ts");
    let bundledDeclarations = join(buildDirectory, "interactors.d.ts");

    await writeFile(
      agentEntrypoint,
      generateAgentEntrypoint(entrypoint, registry, matchers),
    );
    await bundleAgent(agentEntrypoint, bundledAgent, dirname(entrypoint));
    let agent = await readFile(bundledAgent, "utf8");

    await writeFile(
      declarationsEntrypoint,
      generateDeclarationsEntrypoint(
        entrypoint,
        interactors,
        matchers,
      ),
    );
    let declarationConfig = await createDeclarationConfig(entrypoint);
    let declarations: string;
    try {
      await bundleDeclarations(
        declarationsEntrypoint,
        bundledDeclarations,
        dirname(entrypoint),
        declarationConfig,
      );

      declarations = await finalizeDeclarations(
        bundledDeclarations,
        registry.registryHash,
      );
      let checkedDeclarations = join(buildDirectory, "checked-interactors.ts");
      await writeFile(checkedDeclarations, declarations);
    } finally {
      await rm(dirname(declarationConfig), { recursive: true });
    }

    await writeFile(
      agentPath,
      `// Generated by @interactors/cli. Do not edit.\n// Registry: ${registry.registryHash}\n${
        wrapBrowserBundle(agent)
      }`,
    );
    await writeFile(registryPath, registryText);
    await writeFile(declarationsPath, declarations);
  } finally {
    await rm(buildDirectory, { recursive: true });
  }

  return { agentPath, registryPath, declarationsPath, registry };
}

async function importEntrypoint(
  entrypoint: string,
): Promise<{ readonly source: Record<string, unknown> }> {
  let result;
  try {
    result = await build({
      banner: {
        js:
          `import { createRequire as __interactorsCreateRequire } from "node:module";\nvar require = __interactorsCreateRequire(${
            JSON.stringify(pathToFileURL(entrypoint).href)
          });`,
      },
      bundle: true,
      format: "esm",
      logLevel: "silent",
      platform: "node",
      plugins: [portableResolver],
      stdin: {
        contents: `import * as definitions from ${
          JSON.stringify(entrypoint)
        };\nexport default definitions;`,
        loader: "ts",
        resolveDir: dirname(entrypoint),
      },
      write: false,
    });
  } catch (error) {
    throw new Error(
      `Unable to load Interactor entrypoint:\n${formatBuildError(error)}`,
    );
  }
  let moduleUrl = `data:text/javascript;base64,${
    Buffer.from(result.outputFiles[0].contents).toString("base64")
  }`;
  let imported = await import(`${moduleUrl}#${crypto.randomUUID()}`) as {
    readonly default: Record<string, unknown>;
  };
  // A module namespace may itself export a callable `then`. Keep it boxed so
  // async-function resolution does not treat that namespace as a thenable.
  return { source: imported.default };
}

function wrapBrowserBundle(bundle: string): string {
  return `(function (require) {\n${bundle}\n})(function (specifier) {
  if (specifier !== "events" && specifier !== "node:events") {
    throw new Error("Unsupported browser dependency: " + specifier);
  }

  class EventEmitter {
    constructor() {
      this.listeners = new Map();
    }

    setMaxListeners() {
      return this;
    }

    on(event, listener) {
      let listeners = this.listeners.get(event) || [];
      listeners.push(listener);
      this.listeners.set(event, listeners);
      return this;
    }

    once(event, listener) {
      let wrapped = (...args) => {
        this.off(event, wrapped);
        listener.apply(this, args);
      };
      return this.on(event, wrapped);
    }

    off(event, listener) {
      let listeners = this.listeners.get(event);
      if (listeners) {
        this.listeners.set(event, listeners.filter((item) => item !== listener));
      }
      return this;
    }

    removeListener(event, listener) {
      return this.off(event, listener);
    }

    emit(event, ...args) {
      let listeners = this.listeners.get(event) || [];
      for (let listener of [...listeners]) {
        listener.apply(this, args);
      }
      return listeners.length > 0;
    }
  }

  return { EventEmitter };
});\n`;
}

function resolveInput(path: string): string {
  return isAbsolute(path) ? path : resolve(path);
}

async function requireFile(path: string): Promise<void> {
  let info;
  try {
    info = await stat(path);
  } catch (error) {
    if (isNotFound(error)) {
      throw new Error(`Interactor entrypoint does not exist: ${path}`);
    }
    throw error;
  }

  if (!info.isFile()) {
    throw new Error(`Interactor entrypoint is not a file: ${path}`);
  }
}

function discoverInteractors(
  source: Record<string, unknown>,
): RegistryInteractor[] {
  let interactors: RegistryInteractor[] = [];

  for (let [id, value] of sortedEntries(source)) {
    let metadata = getInteractorConstructorMetadata(value);
    if (metadata) {
      validateDefinitionName("Interactor", id, metadata.name);
      validateInteractorMethods(id, metadata.actions, metadata.filters);
      interactors.push({
        id,
        name: metadata.name,
        actions: [...metadata.actions],
        filters: [...metadata.filters],
      });
    }
  }

  return interactors;
}

function validateInteractorMethods(
  id: string,
  actions: readonly string[],
  filters: readonly string[],
): void {
  let actionNames = new Set(actions);
  for (let name of [...actions, ...filters]) {
    if (name.length === 0) {
      throw new Error(
        `Interactor ${JSON.stringify(id)} declares an empty method name`,
      );
    }
    if (reservedInteractorMethods.has(name)) {
      throw new Error(
        `Interactor ${JSON.stringify(id)} declares reserved method ${
          JSON.stringify(name)
        }`,
      );
    }
    if (actionNames.has(name) && filters.includes(name)) {
      throw new Error(
        `Interactor ${JSON.stringify(id)} declares ${
          JSON.stringify(name)
        } as both an action and a filter`,
      );
    }
  }
}

function discoverMatchers(
  source: Record<string, unknown>,
): DiscoveredMatcher[] {
  let matchers = new Map<string, DiscoveredMatcher>();

  for (let [id, value] of sortedEntries(builtins)) {
    let metadata = getMatcherConstructorMetadata(value);
    if (!metadata) {
      throw new Error(`Built-in matcher ${id} does not expose metadata`);
    }
    validateDefinitionName("Matcher", id, metadata.name);
    matchers.set(id, {
      id,
      name: metadata.name,
      source: "builtin",
      builtinExport: id,
    });
  }

  for (let [id, value] of sortedEntries(source)) {
    let metadata = getMatcherConstructorMetadata(value);
    if (metadata) {
      validateDefinitionName("Matcher", id, metadata.name);
      matchers.set(id, {
        id,
        name: metadata.name,
        source: "entrypoint",
      });
    }
  }

  return [...matchers.values()].sort(byId);
}

function validateDefinitionName(
  kind: "Interactor" | "Matcher",
  id: string,
  name: string,
): void {
  if (name.length === 0) {
    throw new Error(`${kind} ${JSON.stringify(id)} has an empty name`);
  }
}

function validateDefinitionIds(
  interactors: readonly RegistryInteractor[],
  matchers: readonly RegistryMatcher[],
): void {
  let interactorIds = new Set(interactors.map(({ id }) => id));

  for (let definition of [...interactors, ...matchers]) {
    if (definition.id === "then") {
      throw new Error('Interactor definitions cannot be exported as "then"');
    }
  }

  for (let matcher of matchers) {
    if (interactorIds.has(matcher.id)) {
      throw new Error(
        `Definition ${
          JSON.stringify(matcher.id)
        } is exported as both an interactor and a matcher`,
      );
    }
  }
}

async function createRegistry(
  interactors: readonly RegistryInteractor[],
  matchers: readonly RegistryMatcher[],
): Promise<Registry> {
  let content = {
    protocolVersion: AGENT_PROTOCOL_VERSION,
    interactors,
    matchers: matchers.map(({ id, name }) => ({ id, name })),
  };
  let registryHash = await sha256(JSON.stringify(content));

  return {
    protocolVersion: AGENT_PROTOCOL_VERSION,
    registryHash,
    interactors,
    matchers: content.matchers,
  };
}

async function sha256(value: string): Promise<string> {
  let digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(value),
  );
  let hex = [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
  return `sha256:${hex}`;
}

function generateAgentEntrypoint(
  entrypoint: string,
  registry: Registry,
  matchers: readonly DiscoveredMatcher[],
): string {
  let sourceUrl = entrypoint;
  let runtimeUrl = fileURLToPath(
    new URL(
      import.meta.url.endsWith(".ts") ? "./agent.ts" : "./agent.js",
      import.meta.url,
    ),
  );
  let coreUrl = "@interactors/core";
  let builtinMatchers = matchers.filter((matcher) =>
    matcher.source === "builtin"
  );
  let builtinImports = builtinMatchers.map((matcher, index) =>
    `${matcher.builtinExport} as __builtinMatcher${index}`
  );
  let matcherValues = matchers.map((matcher) => {
    if (matcher.source === "entrypoint") {
      return `    [${JSON.stringify(matcher.id)}, source[${
        JSON.stringify(matcher.id)
      }]],`;
    }
    let index = builtinMatchers.indexOf(matcher);
    return `    [${JSON.stringify(matcher.id)}, __builtinMatcher${index}],`;
  });
  let interactorValues = registry.interactors.map((interactor) =>
    `    [${JSON.stringify(interactor.id)}, source[${
      JSON.stringify(interactor.id)
    }]],`
  );

  return `import * as source from ${JSON.stringify(sourceUrl)};
import { ${builtinImports.join(", ")} } from ${JSON.stringify(coreUrl)};
import { installAgent } from ${JSON.stringify(runtimeUrl)};

installAgent({
  registry: ${JSON.stringify(registry)},
  interactors: new Map([
${interactorValues.join("\n")}
  ]),
  matchers: new Map([
${matcherValues.join("\n")}
  ]),
});
`;
}

function generateDeclarationsEntrypoint(
  entrypoint: string,
  interactors: readonly RegistryInteractor[],
  matchers: readonly DiscoveredMatcher[],
): string {
  let sourceUrl = entrypoint;
  let names = [
    ...interactors.map(({ id }) => id),
    ...matchers
      .filter(({ source }) => source === "entrypoint")
      .map(({ id }) => id),
  ];

  for (let name of names) {
    if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) || name === "default") {
      throw new Error(
        `Cannot generate declarations for export ${
          JSON.stringify(name)
        }. Interactors and custom matchers must use named exports.`,
      );
    }
  }

  if (names.length === 0) {
    return "export {};\n";
  }

  let imports = names.map((name, index) => `  ${name} as __definition${index}`);
  let exports = names.map((name, index) =>
    `export const ${name} = __definition${index};`
  );

  return `import {\n${imports.join(",\n")}\n} from ${
    JSON.stringify(sourceUrl)
  };\n\n${exports.join("\n")}\n`;
}

async function bundleAgent(
  entrypoint: string,
  outfile: string,
  cwd: string,
): Promise<void> {
  let result;
  try {
    result = await build({
      absWorkingDir: cwd,
      bundle: true,
      entryPoints: [entrypoint],
      external: ["events", "node:events", "node:*"],
      format: "iife",
      logLevel: "silent",
      metafile: true,
      minify: true,
      outfile,
      platform: "browser",
      plugins: [portableResolver],
    });
  } catch (error) {
    throw new Error(
      `Unable to bundle browser agent:\n${formatBuildError(error)}`,
    );
  }

  let unsupported = new Set<string>();
  for (let output of Object.values(result.metafile.outputs)) {
    for (let imported of output.imports) {
      if (
        imported.external && imported.path !== "events" &&
        imported.path !== "node:events"
      ) {
        unsupported.add(imported.path);
      }
    }
  }

  if (unsupported.size > 0) {
    throw new Error(
      `Browser agent depends on unsupported external ${
        unsupported.size === 1 ? "module" : "modules"
      }: ${
        [...unsupported].sort().map((specifier) => JSON.stringify(specifier))
          .join(", ")
      }`,
    );
  }
}

async function bundleDeclarations(
  entrypoint: string,
  declarationPath: string,
  cwd: string,
  config: string,
): Promise<void> {
  void cwd;
  try {
    let configFile = ts.readConfigFile(config, ts.sys.readFile);
    if (configFile.error) {
      throw new Error(formatTypeScriptDiagnostics([configFile.error]));
    }
    let parsed = ts.parseJsonConfigFileContent(
      configFile.config,
      ts.sys,
      dirname(config),
      undefined,
      config,
    );
    if (parsed.errors.length > 0) {
      throw new Error(formatTypeScriptDiagnostics(parsed.errors));
    }
    let program = ts.createProgram([entrypoint], parsed.options);
    let declarations: string | undefined;
    let result = program.emit(
      program.getSourceFile(entrypoint),
      (path, text) => {
        if (path.endsWith(".d.ts")) {
          declarations = text;
        }
      },
      undefined,
      true,
    );
    if (result.emitSkipped || !declarations) {
      throw new Error(formatTypeScriptDiagnostics(result.diagnostics));
    }
    await writeFile(declarationPath, declarations);
  } catch (error) {
    throw new Error(
      `Unable to generate Interactor declarations:\n${formatBuildError(error)}`,
    );
  }
}

async function createDeclarationConfig(entrypoint: string): Promise<string> {
  let discovered = await findDenoConfig(dirname(entrypoint));
  let directory = discovered ? dirname(discovered.path) : dirname(entrypoint);
  let configDirectory = await mkdtemp(
    join(directory, ".interactors-declarations-"),
  );
  let paths = discovered
    ? await workspaceTypePaths(
      discovered.path,
      discovered.config,
      configDirectory,
    )
    : {};
  let scoped = {
    compilerOptions: {
      allowImportingTsExtensions: true,
      declaration: true,
      emitDeclarationOnly: true,
      lib: ["ESNext", "DOM", "DOM.Iterable"],
      module: "ESNext",
      moduleResolution: "Bundler",
      noCheck: true,
      paths,
      skipLibCheck: true,
      target: "ES2020",
    },
    files: [entrypoint],
  };
  let path = join(configDirectory, "tsconfig.json");

  await writeFile(path, `${JSON.stringify(scoped, null, 2)}\n`, { flag: "wx" });
  return path;
}

async function workspaceTypePaths(
  configPath: string,
  config: Record<string, unknown>,
  configDirectory: string,
): Promise<Record<string, string[]>> {
  if (!Array.isArray(config.workspace)) {
    return {};
  }
  let root = dirname(configPath);
  let paths: Record<string, string[]> = {};
  for (let member of config.workspace) {
    if (typeof member !== "string") {
      continue;
    }
    let packageDirectory = resolve(root, member);
    try {
      let manifest = parseJsonc(
        await readFile(join(packageDirectory, "deno.json"), "utf8"),
      );
      if (!isRecord(manifest) || typeof manifest.name !== "string") {
        continue;
      }
      let entry = isRecord(manifest.exports) &&
          typeof manifest.exports["."] === "string"
        ? manifest.exports["."]
        : "./mod.ts";
      let packageLink = join(
        configDirectory,
        "node_modules",
        ...manifest.name.split("/"),
      );
      await mkdir(packageLink, { recursive: true });
      await writeFile(
        join(packageLink, "package.json"),
        JSON.stringify({ name: manifest.name, types: "./index.d.ts" }),
      );
      await writeFile(
        join(packageLink, "index.d.ts"),
        `export * from ${JSON.stringify(resolve(packageDirectory, entry))};\n`,
      );
      paths[manifest.name] = [join(packageLink, "index.d.ts")];
    } catch (error) {
      if (!isNotFound(error)) {
        throw error;
      }
    }
  }
  return paths;
}

async function findDenoConfig(
  start: string,
): Promise<
  | { readonly path: string; readonly config: Record<string, unknown> }
  | undefined
> {
  let nearest:
    | { readonly path: string; readonly config: Record<string, unknown> }
    | undefined;
  let directory = start;

  while (true) {
    for (let filename of ["deno.json", "deno.jsonc"]) {
      let path = join(directory, filename);
      try {
        let parsed = parseJsonc(await readFile(path, "utf8"));
        if (!isRecord(parsed)) {
          throw new Error(`Deno configuration must contain an object: ${path}`);
        }
        let discovered = { path, config: parsed };
        nearest ??= discovered;
        if (parsed.workspace !== undefined) {
          return discovered;
        }
      } catch (error) {
        if (!isNotFound(error)) {
          throw error;
        }
      }
    }

    let parent = dirname(directory);
    if (parent === directory) {
      return nearest;
    }
    directory = parent;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function finalizeDeclarations(
  path: string,
  registryHash: string,
): Promise<string> {
  let declarations = await readFile(path, "utf8");

  let localImport = declarations.match(
    /(?:import\(|from\s+)["'](file:[^"']+|\.{1,2}\/[^"']+)/,
  );
  if (localImport) {
    throw new Error(
      `Generated declarations depend on local source ${
        JSON.stringify(localImport[1])
      }. Re-export that type from the Interactor entrypoint or define it there.`,
    );
  }

  return `// Generated by @interactors/cli. Do not edit.\n// Registry: ${registryHash}\n\n${declarations.trim()}\n`;
}

function isNotFound(error: unknown): boolean {
  return isRecord(error) && error.code === "ENOENT";
}

function formatBuildError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function formatTypeScriptDiagnostics(
  diagnostics: readonly ts.Diagnostic[],
): string {
  return ts.formatDiagnostics(diagnostics, {
    getCanonicalFileName: (path) => path,
    getCurrentDirectory: ts.sys.getCurrentDirectory,
    getNewLine: () => "\n",
  }).trim();
}

function sortedEntries<T>(value: Record<string, T>): [string, T][] {
  return Object.entries(value).sort(([left], [right]) =>
    left < right ? -1 : left > right ? 1 : 0
  );
}

function byId(left: { id: string }, right: { id: string }): number {
  return left.id < right.id ? -1 : left.id > right.id ? 1 : 0;
}
