name: Changeset

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    name: Create Changeset PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v3
        with:
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: yarn
      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          commit: "Version packages"
          title: "Version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
