name: Changeset

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    name: Create Changeset PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v3
        with:
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: yarn

      - name: Commit Signing
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.FRONTSIDEJACK_GPG_KEY }}
          passphrase: ${{ secrets.FRONTSIDEJACK_GPG_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          commit: "Version packages"
          title: "Version packages"
          version: yarn changeset version && yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
