name: covector preview
on: pull_request

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v1
      - run: npm ci --ignore-scripts
      - run: npm run prepack
      - name: covector preview
        uses: ./packages/action
        id: covector
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: preview
