name: Preview

on:
  pull_request:
    branches:
      - main

jobs:
  publish-previews:
    name: Publish Preview Packages
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        registry-url: https://registry.npmjs.org
    - name: Publish PR Preview
      uses: thefrontside/actions/publish-pr-preview@mk/preview-fix
      with:
        INSTALL_SCRIPT: yarn install && yarn prepack:all
      env:
        GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
