name: Release

on:
  push:
    branches:
      - main

jobs:
  publish-releases:
    name: Publish Releases
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Publish Releases
      uses: thefrontside/actions/synchronize-with-npm@v1.6
      with:
        before_all: yarn prepack:all
        npm_publish: yarn publish
        ignore: website
      env:
        GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
