name: Publish

on:
  push:
    tags:
      - "@interactors/*-v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish-to-npm:
    if: startsWith(github.ref, 'refs/tags/@interactors')
    name: NPM ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v2

      - name: Determine Package
        id: pkg
        run: deno task context-from-git-tag --gitTag ${{ github.ref }}

      - name: Generate NPM Packages
        run: deno task build:npm ${{ steps.pkg.outputs.working-directory }}

      - name: Publish Releases
        working-directory: ${{ steps.pkg.outputs.working-directory }}/build/npm
        run: npm publish --provenance --access public --tag ${{ steps.pkg.outputs.npm-tag }}
