name: Release

on:
  push:
    branches:
      - main

jobs:
  publish-releases:
    name: Publish Releases
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: yarn install && yarn prepack:all
    - name: Publish Releases
      uses: thefrontside/actions/synchronize-with-npm@v2
      env:
        GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
