name: Run tests

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v3
        with:
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: yarn
      - name: Prepack
        run: yarn prepack
      # NOTE: this will be enabled when we migrate to Deno  
      # - name: Lint
      #   run: yarn lint
      - name: Test
        run: yarn test
