name: Run tests

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: |
            deno run -A npm:playwright install chromium
            deno run -A packages/cli/src/main.ts build
            deno test -A
